name: Generic System Release Stage

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [fe, task-manager, title-generator]

    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Get the latest image from Docker Hub for ${{ matrix.service }}
        id: get-latest-tag
        run: |
          LATEST_TAG=$(curl -s "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}/tags" | jq -r '.results | sort_by(.last_updated) | last(.[]).name')
          echo "The latest tag is: $LATEST_TAG"
          echo "::set-output name=LATEST_TAG::$LATEST_TAG"

      - name: SSH and Deploy to GCP VM
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.DOCKER_USERNAME }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            docker stop ${{ matrix.service }} || true
            docker rm ${{ matrix.service }} || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:${{ steps.get-latest-tag.outputs.LATEST_TAG }}
            if [ "${{ matrix.service }}" = "fe" ]; then
              docker run -d --name fe -p 80:80 -e VITE_API_URL="${{ secrets.VM_IP }}" ${{ secrets.DOCKER_USERNAME }}/fe:${{ steps.get-latest-tag.outputs.LATEST_TAG }}
            elif [ "${{ matrix.service }}" = "task-manager" ]; then
              docker run -d --name task-manager -p 3001:3001 -e MONGO_URI="${{ secrets.MONGO_URI }}" ${{ secrets.DOCKER_USERNAME }}/task-manager:${{ steps.get-latest-tag.outputs.LATEST_TAG }}
            else
              docker run -d --name title-generator -p 3002:3002 ${{ secrets.DOCKER_USERNAME }}/title-generator:${{ steps.get-latest-tag.outputs.LATEST_TAG }}
            fi
