name: Generic System Release Stage

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [fe, task-manager, title-generator]

    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: SSH and Deploy to GCP VM
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.VM_IP }}
          username: josegarrera
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            docker stop ${{ matrix.service }} || true
            docker rm ${{ matrix.service }} || true
            docker pull josegarrera/${{ matrix.service }}:${{ github.sha }}
            if [ "${{ matrix.service }}" = "fe" ]; then
              docker run -d --name fe -p 80:80 \
                -e VITE_API_URL="${{ secrets.VM_IP }}" \
                josegarrera/fe:${{ github.sha }}
            elif [ "${{ matrix.service }}" = "task-manager" ]; then
              docker run -d --name task-manager -p 3001:3001 \
                -e MONGO_URI="${{ secrets.MONGO_URI }}" \
                josegarrera/task-manager:${{ github.sha }}
            else
              docker run -d --name title-generator -p 3002:3002 \
                josegarrera/title-generator:${{ github.sha }}
            fi
