name: UAT Stage

on:
  workflow_dispatch:

jobs:
  uat-release:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Generic System Release
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const workflow = 'Generic System Release Stage';
            const response = await github.actions.listRepoWorkflows({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100,
            });

            // Mostrar el resultado completo para depuración
            console.log('Response data:', response);

            // Obtener el ID del workflow
            const workflow_id = response.data.workflows.find(w => w.name === workflow)?.id;

            if (!workflow_id) {
              throw new Error(`No workflow found with name: ${workflow}`);
            }

            // Desencadenar el workflow
            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflow_id,
              ref: context.ref,
            });

      - name: Run Smoke Tests
        run: echo "Running smoke tests..." && npm run test

